# -*- coding: utf-8 -*-
"""rekom KDrama.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1h4Gc2CBXRrhleGAc21K09DMI0EuhecaD

# Rekomendasi K-Drama Berdasarkan Genre

> Notebook ini berisi program sederhana untuk memberikan rekomendasi K-Drama berdasarkan genre yang dipilih pengguna.
"""

from google.colab import drive
drive.mount('/content/drive')

import pandas as pd

# Muat dataset
data = pd.read_csv('/content/drive/MyDrive/sistem_rekom/kdrama.csv')

print('Jumlah data review :', len(data))

"""# Data Understanding"""

# Ukuran dan struktur data
print("Jumlah data:", data.shape)
data.info()

"""- **Jumlah data:** 250 baris dan 17 kolom.

- **Tipe Data:**
  - Terdapat **14 kolom** bertipe **object**. Biasanya ini adalah fitur kategoris atau teks. Kolom-kolom tersebut adalah:
    - Name
    - Aired Date
    - Original Network
    - Aired On
    - Duration
    - Content Rating
    - Synopsis
    - Genre
    - Tags
    - Director
    - Screenwriter
    - Cast
    - Production companies
    - Rank
  - Terdapat **2 kolom** bertipe **int64**, yang merupakan data numerik:
    - Year of release
    - Number of Episodes
  - Terdapat **1 kolom** bertipe **float64**:
    - Rating
"""

data.head()

print(f'Pada Dataset Terdapat {data.shape[0]} Table dan {data.shape[1]} columns.')

for i, (nama_kolom, jumlah) in enumerate(data.count().items(), 1):
    print(f"Kolom {i:2d}: {nama_kolom} → Berjumlah : {jumlah}")

#mengecek data apakah terdapat data yang duplikat

data.duplicated().sum()
print(f'Jumlah data duplikat : {data.duplicated().sum()}')

# mengecek data apakah ada missing value

data.isnull().sum()

"""terdapat missing value pada kolom Content Rating, Director, Screenwriter, dan Production companies"""

# ternyata dataset ini ada missing value sehingga dilakukan penghapusan missing value

data = data.dropna()

# cek kembali missing value apakah masih ada

data.isnull().sum()

"""missing value sudah teratasi

# Exploratory Data Analysis (EDA)
"""

data.columns

"""Kolom datasets anime memiliki informasi berikut:

*    Name : Judul KDrama
*    Aired Date : Tanggal dari saat hingga KDrama pertama kali ditayangkan.
*    Year of release : Tahun rilis KDrama
*    Original Network : Penayangan KDrama
*    Aired On : Hari-hari dalam seminggu saat KDrama ditayangkan.
*    Number of Episodes : Jumlah episode yang ada
*    Duration : Lama penayangan (dalam jam dan menit)
*    Content Rating : Batasan usia
*    Rating : Skor atau penilaian yang diberikan penonton pada KDrama
*    Sypnosis : Sipnosis dari KDrama
*    Genre : Jenis KDrama (Life, Drama, Romantic, dan lainnya)
*    Tags : Tema
*    Director : Sutradara
*    Screenwriter : Pnulis
*    Cast : Pemeran
*    Production companies : Perusahaan yang memproduksi KDrama
*    Rank : Peringkat KDrama

# Visualization
"""

import seaborn as sns
import matplotlib.pyplot as plt

plt.figure(figsize=(8,5))
sns.countplot(data=data, x='Rating', palette='pastel')
plt.title("Distribusi Rating KDrama")
plt.xlabel("Rating")
plt.ylabel("Jumlah Review")
plt.show()

"""menunjukkan distribusi rating yang ada pada dataset KDrama"""

# Judul terpopuler berdasarkan jumlah review
top_names = data['Name'].value_counts().head(10)

plt.figure(figsize=(10,5))
sns.barplot(x=top_names.values, y=top_names.index, palette='Set2')
plt.title("10 Judul KDrama dengan Review Terbanyak")
plt.xlabel("Jumlah Review")
plt.ylabel("Judul KDrama")
plt.show()

"""didapatkan 10 teratas judul KDrama yang paling banyak di review oleh penonton"""

# 10 Genre dengan Review Terbanyak
top_genres = data['Genre'].value_counts().head(10)

plt.figure(figsize=(10,5))
sns.barplot(x=top_genres.values, y=top_genres.index, palette='magma')
plt.title("10 Genre KDrama dengan Review Terbanyak")
plt.xlabel("Jumlah Review")
plt.ylabel("Genre KDrama")
plt.show()

"""didapatkan 10 genre yang telah banyak di review oleh penonton"""

# Genre dengan rating tertinggi
top_rated = data[['Genre', 'Rating']].groupby('Genre').mean().sort_values('Rating', ascending=False).head(10)

plt.figure(figsize=(10,5))
sns.barplot(x=top_rated['Rating'], y=top_rated.index, palette='Blues_d')
plt.title("10 Genre dengan Rating Tertinggi")
plt.xlabel("Rating Rata-rata")
plt.ylabel("Nama Genre")
plt.show()

"""didapatkan 10 genre dengan rating tertinggi"""

# Judul dengan jumlah review terbanyak
top_names = data['Name'].value_counts().head(10).index

# Rata-rata rating judul tersebut
mean_rating_top_names = data[data['Name'].isin(top_names)].groupby('Name')['Rating'].mean().sort_values(ascending=False)

plt.figure(figsize=(10,5))
sns.barplot(x=mean_rating_top_names.values, y=mean_rating_top_names.index, palette='crest')
plt.title("Rata-rata Rating dari Judul dengan Review Terbanyak")
plt.xlabel("Rata-rata Rating")
plt.ylabel("Nama Judul")
plt.show()

"""didapatkan rata rata rating dari judul dengan review terbanyak"""

import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

# Bersihkan data
data = data.dropna(subset=['Year of release'])
data['Year of release'] = data['Year of release'].astype(int)

# Plot histogram
plt.figure(figsize=(12, 6))
sns.histplot(data=data, x='Year of release', bins=50)
plt.title('Distribusi Sebaran Tahun Pertama Kali di Rilis', fontsize=15, pad=15)

# Atur ticks di sumbu X agar hanya tampil tahun bulat
min_year = data['Year of release'].min()
max_year = data['Year of release'].max()
plt.xticks(np.arange(min_year, max_year + 1, step=2), rotation=45)

plt.tight_layout()
plt.show()

"""dilakukan visualisasi persebaran tahun pertama ketika rilis dari masing-masing judul KDrama"""

# Korelasi antara Rating dan Judul
plt.figure(figsize=(8,5))
sns.scatterplot(data=data, x='Name', y='Rating', alpha=0.6, color='purple')
plt.title("Korelasi antara Rating dan Judul KDrama")
plt.xlabel("Judul")
plt.ylabel("Rating")
plt.show()

"""scatterplot diatas menunjukkan korelasi antara rating dan judul"""

# Korelasi antara Rating dan Genre
plt.figure(figsize=(8,5))
sns.scatterplot(data=data, x='Genre', y='Rating', alpha=0.6, color='green')
plt.title("Korelasi antara Rating dan Genre KDrama")
plt.xlabel("Genre")
plt.ylabel("Rating")
plt.show()

"""scatterplot diatas menunjukkan korelasi antara rating dan genre

# Data Preparation
"""

import re

# melakukan penghapusan link pada judul KDrama
def text_cleaning(text):
  text = re.sub(r"[^\w\s]", "", text)
  text = re.sub(r"https?://[^\s]+", "", text)
  return text

data['Name'] = data['Name'].apply(text_cleaning)

# dilakukan pengecekan ulang pada data yang duplikat

data.duplicated().sum()
print(f'Jumlah data duplikat : {data.duplicated().sum()}')

# dilakukan pengecekan ulang pada data yang memiliki missing value

data.isnull().sum()

data.describe().T

"""Fungsi `describe()` menampilkan statistik ringkasan untuk setiap kolom, seperti jumlah data (count), rata-rata (mean), standar deviasi (std), nilai minimum (min), kuartil (25%, 50%, 75%), dan nilai maksimum (max).

# Model Development
"""

data

data = data.drop(columns=[
    'Aired Date',
    'Year of release',
    'Aired On',
    'Number of Episodes',
    'Duration',
    'Content Rating',
    'Synopsis',
    'Tags',
    'Director',
    'Screenwriter',
    'Cast',
    'Rank'
])

"""Melakukan penghapusan pada kolom yang tidak dibutuhkan"""

data

"""# Model Content Based Filtering (menggunakan kdrama_recommendations)"""

from sklearn.feature_extraction.text import TfidfVectorizer

# Buat TF-IDF Vectorizer dan fit data pada 'Genre'
tfid = TfidfVectorizer()
tfid_matrix = tfid.fit_transform(data['Genre'])  # Gunakan Genre sebagai fitur

tfidf_matrix = tfid.fit_transform(data['Genre'])

tfidf_matrix.shape

pd.DataFrame(
    tfidf_matrix.todense(),
    columns=tfid.get_feature_names_out(),
    index=data.Genre
).sample(22, axis=1).sample(10, axis=0)

"""Matriks ini menunjukkan korelasi antara KDrama terhadap kategori yang dipilih."""

from sklearn.metrics.pairwise import cosine_similarity

cosine_sim = cosine_similarity(tfidf_matrix)
cosine_sim

cosine_sim_df = pd.DataFrame(cosine_sim, index=data['Name'], columns=data['Name'])
print('Shape:', cosine_sim_df.shape)

# Melihat similarity matrix
cosine_sim_df.sample(5, axis=1).sample(5, axis=0)

def kdrama_recommendations(kdrama_name, similarity_data=cosine_sim_df, items=data[['Name','Genre']], k=5):

    index = similarity_data.loc[:,kdrama_name].to_numpy().argpartition(
        range(-1, -k, -1))

    closest = similarity_data.columns[index[-1:-(k+2):-1]]
    closest = closest.drop(kdrama_name, errors='ignore')

    return pd.DataFrame(closest).merge(items).head(k)

data[data.Name.eq('Memory')]

kdrama_recommendations('Memory')

"""Sistem telah berhasil merekomendasikan top 5 dari judul KDrama yang mirip dengan 'Memory'"""

def kdrama_recommendations_genre_rating(kdrama_name, similarity_data=cosine_sim_df, items=data[['Name','Genre','Rating']], top_n=5):
    # Cari index drama berdasarkan cosine similarity
    index = similarity_data.loc[:, kdrama_name].to_numpy().argpartition(
        range(-1, -top_n-1, -1))

    closest = similarity_data.columns[index[-1:-(top_n+2):-1]]
    closest = closest.drop(kdrama_name, errors='ignore')

    # Gabungkan dan urutkan berdasarkan rating
    result = pd.DataFrame(closest).merge(items)
    return result.sort_values(by='Rating', ascending=False).head(top_n)

# Tes output genre + rating
kdrama_recommendations_genre_rating('Memory', top_n=10)

"""# Evaluation (Precision)

Untuk mengevaluasi sistem rekomendasi Content-Based Filtering (CBF), digunakan metrik **Precision**.

**Definisi Precision:**  
Precision = (Jumlah rekomendasi yang relevan) / (Jumlah total rekomendasi)

Dilakukan evaluasi pada 2 skema:  
- **Skema 1**: Berdasarkan Genre saja
- **Skema 2**: Berdasarkan Genre + Rating
"""

def calculate_precision(recommended_items, target_genre):
    if not recommended_items:
        return 0
    relevant = sum(1 for item in recommended_items
                   if target_genre in item['Genre'])
    return relevant / len(recommended_items)

# Skema 1: CBF berdasarkan Genre saja
def recommend_genre_only(user_genre, data, top_n=5):
    recs = []
    for _, row in data.iterrows():
        if user_genre in row['Genre']:
            recs.append({
                'title': row['Name'],
                'Genre': row['Genre'],
                'rating': row['Rating']
            })
    np.random.shuffle(recs)
    return recs[:top_n]

# Skema 2: CBF berdasarkan Genre + Rating
def recommend_genre_rating(user_genre, data, top_n=5):
    recs = []
    for _, row in data.iterrows():
        if user_genre in row['Genre']:
            recs.append({
                'title': row['Name'],
                'Genre': row['Genre'],
                'rating': row['Rating']
            })
    recs = sorted(recs, key=lambda x: x['rating'], reverse=True)
    return recs[:top_n]

# Asumsikan user suka genre 'Romance'
target_genre = 'Romance'

# Skema 1: Genre Only
recs_genre_only = recommend_genre_only(target_genre, data)
precision_genre_only = calculate_precision(recs_genre_only, target_genre)
print(f"Precision (Genre only): {precision_genre_only:.2f}")

# Skema 2: Genre + Rating
recs_genre_rating = recommend_genre_rating(target_genre, data)
precision_genre_rating = calculate_precision(recs_genre_rating, target_genre)
print(f"Precision (Genre + Rating): {precision_genre_rating:.2f}")

# Misal, memilih beberapa drama untuk uji genre 'Romance'
test_set = data[data['Genre'].str.contains('Romance', na=False)].sample(10)

# Recall: berapa banyak rekomendasi yang relevan ditemukan
def calculate_recall(recommended_items, target_genre, total_relevant_items):
    relevant = sum(1 for item in recommended_items if target_genre in item['Genre'])
    return relevant / total_relevant_items

# F1-Score: menggabungkan precision dan recall
def calculate_f1(precision, recall):
    if precision + recall == 0:
        return 0
    return 2 * (precision * recall) / (precision + recall)

genres = ['Romance', 'Comedy', 'Thriller', 'Action']  # Contoh genre
precision_results = []
recall_results = []
f1_results = []
for genre in genres:
    # Generate rekomendasi untuk setiap genre
    recs = recommend_genre_only(genre, data)
    precision = calculate_precision(recs, genre)
    recall = calculate_recall(recs, genre, total_relevant_items=len(data[data['Genre'].str.contains(genre)]))
    f1 = calculate_f1(precision, recall)

    precision_results.append(precision)
    recall_results.append(recall)
    f1_results.append(f1)

print(f"Average Precision: {np.mean(precision_results):.2f}")
print(f"Average Recall: {np.mean(recall_results):.2f}")
print(f"Average F1-Score: {np.mean(f1_results):.2f}")

"""Precision 1.00 → semua rekomendasi yang diberikan relevan (genre cocok).

Recall 0.07 → hanya 7 % dari semua drama Romance berhasil direkomendasikan—banyak yang terlewat.

F1-Score 0.13 → gabungan keduanya rendah, menandakan model terlalu selektif sehingga meski tepat, cakupan rekomendasi sangat sempit.

# Additional Analysis Clustering

Analisis ini digunakan untuk memahami struktur distribusi data KDrama berdasarkan fitur yang tersedia.  
Namun, hasil ini **bukan digunakan untuk mengevaluasi performa sistem rekomendasi**.
"""

import pandas as pd

def Recommended_model(kdrama_name: str, recommend_kdrama: int = 5):
    print(f'Apabila pengguna menyukai drama: {kdrama_name}\nBerikut ini adalah drama yang juga mungkin akan disukai:')

    # Dapatkan genre dari drama yang dipilih
    target_genre = data.loc[data['Name'] == kdrama_name, 'Genre'].values[0]

    # Panggil CBF recommendation (mengembalikan list of dict)
    recs = recommend_genre_only(target_genre, data, top_n=recommend_kdrama)

    # Konversi ke DataFrame, rename kolom, lalu head()
    df_recs = pd.DataFrame(recs).rename(columns={'title': 'Name'})
    return df_recs[['Name', 'Genre']].head(recommend_kdrama)

Recommended_model("Memory")

from sklearn.feature_extraction.text import TfidfVectorizer

# 1) Buat TF-IDF matrix dari kolom Genre
tfidf = TfidfVectorizer(token_pattern=r'(?u)\b\w+\b')
tfidf_matrix = tfidf.fit_transform(data['Genre'])

# 2) Simpan sebagai DataFrame dengan index nama drama
data_kdrama = pd.DataFrame(tfidf_matrix.toarray(),
                           index=data['Name'],
                           columns=tfidf.get_feature_names_out())

# 1) Gunakan kolom Rating dari data
data_kdrama = data[['Rating']].copy()

# Gabungkan Rating dan Genre
from sklearn.feature_extraction.text import TfidfVectorizer

# 1) Buat TF-IDF matrix dari genre
tfidf = TfidfVectorizer(token_pattern=r'(?u)\b\w+\b')
tfidf_matrix = tfidf.fit_transform(data['Genre'])

# 2) Gabungkan dengan rating
import numpy as np
data_kdrama = np.hstack([tfidf_matrix.toarray(), data[['Rating']].values])

from sklearn.cluster import KMeans
from sklearn.metrics import calinski_harabasz_score, davies_bouldin_score

# Lakukan clustering
kmeans = KMeans(n_clusters=5, random_state=42)
cluster_labels = kmeans.fit_predict(data_kdrama)

# Hitung metrik
ch_score = calinski_harabasz_score(data_kdrama, cluster_labels)
db_score = davies_bouldin_score(data_kdrama, cluster_labels)

print("Calinski-Harabasz Score:", ch_score)
print("Davies-Bouldin Score:", db_score)

"""Calinski-Harabasz (20.65): Pemisahan klaster tergolong cukup baik—nilai yang lebih tinggi berarti klaster lebih terpisah.

Davies-Bouldin (2.61): Ada tumpang tindih antar klaster—nilai lebih rendah (<1) yang ideal menunjukkan klaster kompak dan terpisah sempurna.
"""